### ISSUE TITLE
bugs report：the blocks are all transparent and cannot be seen

### ISSUE THREAD

**Issue by AugFUZE** [Poisoned-Honey/ForgetMeNot-Shaders#4]
[material_color.txt](https://github.com/Poisoned-Honey/ForgetMeNot-Shaders/files/9861280/material_color.txt)

[material_color_terrain.txt](https://github.com/Poisoned-Honey/ForgetMeNot-Shaders/files/9861282/material_color_terrain.txt)

version 1.19.2-Fabric 0.14.10
graphics card GTX1660
mods ： only fabric API and canvas-fabric-mc119-1.0.2379
system： windows 10

The canvas indicates an error.
Only the sky renders normally, and the blocks are all transparent and cannot be seen
![V8MR9%MP@NU`OPU8 6FH{VP](https://user-images.githubusercontent.com/79316204/197807333-5f93b5ac-6c9a-4025-ba2e-619972b45bad.png)
![V3COUQR)QT ZQ84JPD$ 0B](https://user-images.githubusercontent.com/79316204/197807479-ec39523c-40b9-47ee-ba9a-620935a60675.png)

**Comment by ambrosia13** [comment]
Thank you for the report. Version 2379 is very old, can you try a [newer version](https://modrinth.com/mod/canvas/version/fabric-mc119-1.0.2494)? I get no issues on the newest version.
