### ISSUE TITLE
Rain renders incorrectly

### ISSUE THREAD

**Issue by AugFUZE** [Poisoned-Honey/ForgetMeNot-Shaders#5]
version 1.19.2-Fabric 0.14.10
graphics card GTX1660
mods ： only fabric API and canvas-fabric-mc119-1.0.2494
shader: Forget-Me-Not_v0.4.1
system： windows 10
![2022-10-27_20 33 19](https://user-images.githubusercontent.com/79316204/198285960-185255d0-8107-48fc-9a51-9316a15c615c.png)
![2022-10-27_20 33 31](https://user-images.githubusercontent.com/79316204/198285971-2384e0a4-b0c5-45c5-9140-b9e81345ea88.png)
When it rains, can only see the rain on the water.
![2022-10-27_20 33 51](https://user-images.githubusercontent.com/79316204/198285977-8a7aaf4d-9ccb-46e6-817a-6340aa88b9a9.png)
![2022-10-27_20 33 56](https://user-images.githubusercontent.com/79316204/198285980-1da6108c-5120-419e-b2dc-a6bd506c7a9d.png)
Illuminated squares (like redstone torche，lantern) are not the same color when placed than when held in your hand.（Haven't done this part of the function yet?）

**Comment by ambrosia13** [comment]
Colored lights are out of scope of Forget-me-not. Colored hand held lights, however, are very easy to support. That won't be fixed. 

Also, rain doesn't happen in the Savanna biome. That is why you can only see them in the river, unless I'm misunderstanding something. Please clarify if I am.
